import {
  Globe,
  RefreshCw,
  ShoppingCart,
  Smartphone,
  Gauge,
  Accessibility,
  PenLine,
  Wrench,
  LayoutGrid,
  Users,
  Settings2,
  Webhook,
  Blocks,
  Database,
  PhoneCall,
  MessagesSquare,
  Workflow,
  Sparkles,
  Compass,
  Contact,
  Boxes,
  Mail,
  Network,
  ArrowRightLeft,
  GraduationCap,
  CheckCheck,
  BellRing,
  LineChart,
  Search,
  Target,
  Share2,
  FileText,
  BarChart3,
  ClipboardCheck,
  Fingerprint,
  FileSignature,
  Cpu,
  Code2,
  Rocket,
  type LucideIcon,
} from "lucide-react";

/**
 * Registre central des icônes utilisées par les pages de service. Le contenu
 * (`content/services/*.ts`) référence une icône par sa **clé** (jamais un
 * composant importé directement), pour rester du JSON-like pur.
 */
export const ICONS = {
  Globe,
  RefreshCw,
  ShoppingCart,
  Smartphone,
  Gauge,
  Accessibility,
  PenLine,
  Wrench,
  LayoutGrid,
  Users,
  Settings2,
  Webhook,
  Blocks,
  Database,
  PhoneCall,
  MessagesSquare,
  Workflow,
  Sparkles,
  Compass,
  Contact,
  Boxes,
  Mail,
  Network,
  ArrowRightLeft,
  GraduationCap,
  CheckCheck,
  BellRing,
  LineChart,
  Search,
  Target,
  Share2,
  FileText,
  BarChart3,
  ClipboardCheck,
  Fingerprint,
  FileSignature,
  Cpu,
  Code2,
  Rocket,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;

export function getIcon(key: IconKey): LucideIcon {
  return ICONS[key];
}
